display_name: Taskinator
package_name: taskinator

maintainer:
  name: Alex Chica
  email: axcavo@gmail.com

priority: optional

section: x11

installed_size: 15700

dependencies:
  - mpv

essential: false

icon: linux/assets/icon.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Task
  - Taskinator

generic_name: API Client

categories:
  - Development
  - Utility

startup_notify: true